<div style="text-align:center;">
    <div class="birk">
        <img src="JO2024.png">
    </div>
</div>

<div style="background-color:#B96CE6; padding:0px 0; color:white; text-align:center;">
    <h1 style="padding-left:50px; font-size:100px; font-weight: bold;">PROJET JO 2024</h1>
</div>

### <a id='toc1_4_1_'></a>[To do :](#toc0_)
Scrape countries codes to loop on each of them (website url modification)  
Link of countries codes : "http://olympanalyt.com/OlympAnalytics.php?param_pagetype=RefCountries&param_dbversion=&param_country=CIV&param_games=ALL&param_sport=ALL"

<div style="background-color:#0082C7;padding:0px; color:white;"text-align:center;">
    <h2 style="padding-left: 40px;">IMPORTATION DES LIBRAIRIES</h2>
</div>

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

<div style="background-color:#0082C7;padding:0px; color:white;">
    <h2 style="padding-left: 40px;">FONCTIONS</h2>
</div>

Avant de commencer à analyser des données, il est important de vérifier que les données sont effectivement disponibles. En vérifiant le code de statut, vous pouvez vous assurer que la requête vers le serveur s'est bien déroulée et que vous avez reçu une réponse

Dans les définitions de fonctions, le texte entre parenthèses après le nom de la fonction est appelé un **paramètre**. Les paramètres sont utilisés pour passer des valeurs à une fonction afin qu'elle puisse les utiliser dans son traitement.

Dans le cas ci-dessous de la fonction **GetHTML(url)**, le paramètre **url** est utilisé pour spécifier l'URL du site web à partir duquel nous voulons obtenir le contenu HTML. Lorsque nous appelons cette fonction, nous devons fournir une valeur pour **url** afin qu'elle puisse exécuter sa logique et récupérer le contenu HTML de cette URL spécifique.

In [2]:
def GetHTML(url) :
    """
    Needed : url website
    Return : HTML text
    """
    response = requests.get(url)

    if response.status_code == 200 :
        print("Response OK, continue.")
    else :
        print("Access impossible.")
    
    return response.text

Dans le cas ci-dessous de la fonction **GetDataframe(html)**, le paramètre **page_medalist** est utilisé pour spécifier le contenu HTML à partir duquel nous voulons extraire les données pour créer un DataFrame. Lorsque nous appelons cette fonction, nous devons fournir le contenu HTML que nous avons récupéré précédemment (par exemple, en appelant GetHTML()).

La raison d'avoir la fonction ci dessous est de modulariser votre code.\
En encapsulant le processus de création du DataFrame dans une fonction distincte, vous pouvez réutiliser cette fonction chaque fois que vous avez besoin de créer un DataFrame à partir des données d'une page web. Cela rend votre code plus lisible, plus modulaire et plus facile à maintenir.\
De plus, cela facilite le partage et la réutilisation du code dans d'autres parties de votre projet ou dans d'autres projets.

In [3]:
def GetDataframe(page_medalist): 

    soup = BeautifulSoup(page_medalist,"html5lib") #parse
    
    # Recherche du bon tableau selon description
    tableau = soup.find("table", class_="simpletable", style="text-align:left;")
    
    # Récupération de la liste (find_all) de toutes les lignes
    rows = tableau.find_all("tr")
    
    # Création du tableau (futur dataframe)
    line_medalist = []
    
    # Sur chaque ligne (= athlète)
    for row in rows :
        describe_athlete = row.text.split() #récupère le texte
        cells = row.find_all("td") #récupère la liste (find_all) de toutes les cellules de la ligne
        if len(cells) == 7 : #si il y a 7 cellules alors c'est un athlète
            medal = cells[0].find('img')['title'][0]  #titre de la médaille
            country = cells[1].find('img')['title']  #pays de l'athlète
            athlete_name = cells[2].text.strip()  #nom de l'athlète
            games = cells[3].find('img')['title']  #jeux olympiques
            sport = cells[4].find('img')['title']  #sport
            event = cells[6].text.strip()  # evénement
    
            #print(cells)
        
            # Ajoute les informations à la liste des athlètes
            line_medalist.append({
                'medal': medal,
                'country': country,
                'athlete_name': athlete_name,
                'games': games,
                'sport': sport,
                'event': event
                })
        else : #sinon ce n'est pas un athlète, passe à la ligne suivante
            next
    medalist = pd.DataFrame(line_medalist)
    return medalist

In [4]:
url = "http://olympanalyt.com/OlympAnalytics.php?param_pagetype=Medals&param_dbversion=&param_country=FRA&param_games=ALL&param_sport=ALL"
html_brut = GetHTML(url)
GetDataframe(html_brut)

Response OK, continue.

,medal,country,athlete_name,games,sport,event
0,1,France,Paul MASSON,Greece,Cycling Track,sprint individual
1,1,France,Paul MASSON,Greece,Cycling Track,1/3km time trial
2,1,France,Paul MASSON,Greece,Cycling Track,10km
3,1,France,Léon FLAMENG,Greece,Cycling Track,100km
4,1,France,Eugène-Henri GRAVELOTTE,Greece,Fencing,foil individual
...,...,...,...,...,...,...
884,2,France,SIMON JuliaFILLON MAILLET QuentinCHEVALIER-BOU...,China,Biathlon,Relay mix
885,2,France,LEDEUX Tess,China,Freestyle Skiing,Big air
886,2,France,TRESPEUCH Chloe,China,Snowboard,Snowboard Cross
887,3,France,FAIVRE Mathieu,China,Alpine Skiing,giant slalom
888,3,France,LAPALUS HugoMANIFICAT MauriceJOUVE RichardPARI...,China,Cross Country Skiing,4x10km relay

<div style="background-color:#0082C7;padding:0px; color:white;">
    <h2 style="padding-left: 40px;">IMPORTATION DES DONNEES ET VERIFICATION ACCES</h2>
</div>

In [5]:
url = "http://olympanalyt.com/OlympAnalytics.php?param_pagetype=Medals&param_dbversion=&param_country=FRA&param_games=ALL&param_sport=ALL"
html_brut = GetHTML(url)

Response OK, continue.

<div style="background-color:#0082C7;padding:0px; color:white;">
    <h2 style="padding-left: 40px;">INFORMATIONS DES DONNEES</h2>
</div>

**html5lib** est une bibliothèque purement python pour l’analyse du HTML.\
Il est conçu pour conformes à la spécification HTML WHATWG, telle qu’elle est mise en œuvre par tous les principaux navigateurs Web.

soup = BeautifulSoup(page_medalist,"html5lib") #parse

**WEB SCRAPING :**

<div style="text-align:center;">
    <div class="birk">
        <img src="scraping.png">
    </div>
</div>

<div style="background-color:#FCB030;padding:0px; color:white;">
    <h3 style="padding-left: 40px;">Récupérer les données d'un pays</h3>
</div>

In [6]:
url = "http://olympanalyt.com/OlympAnalytics.php?param_pagetype=Medals&param_dbversion=&param_country=FRA&param_games=ALL&param_sport=ALL"
html_brut = GetHTML(url)
df = GetDataframe(html_brut)
df

Response OK, continue.

,medal,country,athlete_name,games,sport,event
0,1,France,Paul MASSON,Greece,Cycling Track,sprint individual
1,1,France,Paul MASSON,Greece,Cycling Track,1/3km time trial
2,1,France,Paul MASSON,Greece,Cycling Track,10km
3,1,France,Léon FLAMENG,Greece,Cycling Track,100km
4,1,France,Eugène-Henri GRAVELOTTE,Greece,Fencing,foil individual
...,...,...,...,...,...,...
884,2,France,SIMON JuliaFILLON MAILLET QuentinCHEVALIER-BOU...,China,Biathlon,Relay mix
885,2,France,LEDEUX Tess,China,Freestyle Skiing,Big air
886,2,France,TRESPEUCH Chloe,China,Snowboard,Snowboard Cross
887,3,France,FAIVRE Mathieu,China,Alpine Skiing,giant slalom
888,3,France,LAPALUS HugoMANIFICAT MauriceJOUVE RichardPARI...,China,Cross Country Skiing,4x10km relay

<div style="background-color:#FCB030;padding:0px; color:white;">
    <h3 style="padding-left: 40px;">Récuperation des codes pays</h3>
</div>

In [7]:
url2 = "http://olympanalyt.com/OlympAnalytics.php?param_pagetype=RefCountries&param_dbversion=&param_country=CIV&param_games=ALL&param_sport=ALL"
html2 = GetHTML(url2)

Response OK, continue.

In [8]:
soup2 = BeautifulSoup(html2,"html5lib")

In [9]:
# Recherche du bon tableau selon description
# Il faut mettre un "_" après class pour differencier avec class
tableau2 = soup2.find_all("table", class_="simpletable", style="text-align:center;")[1]


# Récupération de la liste (find_all) de toutes les lignes
rows2 = tableau2.find_all("tr")



# Création du tableau (futur dataframe)
country_jo = []



# Sur chaque ligne (= athlète)
for row2 in rows2 :
    cells2 = row2.find_all("td") #récupère la liste (find_all) de toutes les cellules de la ligne
    if len(cells2) == 5 and len(cells2[0].text.strip())!=0:
        Code = cells2[0].text.strip()
        Country2 = cells2[1].text.strip()
        Continent = cells2[2].text.strip()  
        First_participation = cells2[3].text.strip() 
        Last_participation = cells2[4].text.strip()

        #print(cells)
    
        # Ajoute les informations à la liste des athlètes
        country_jo.append({
            'Code': Code,
            'Country': Country2,
            'Continent': Continent,
            'First_participation': First_participation,
            'Last_participation': Last_participation
            })
    else : 
        next

In [10]:
# Création dataframe
df_country = pd.DataFrame(country_jo)
df_country

,Code,Country,Continent,First_participation,Last_participation
0,AFG,Afghanistan,Asia,1936,2021
1,ALB,Albania,Europe,1972,2022
2,ALG,Algeria,Africa,1964,2021
3,ASA,American Samoa,Oceania,1988,2022
4,AND,Andorra,Europe,1976,2022
...,...,...,...,...,...
226,YAR,Yemen Arab Republic,,1984,1988
227,YMD,Yemen Democratic Republic,,1988,1988
228,ZZX,Mixed Team,,1896,1904
229,IOA,Independent Olympic Athletes,,2000,2016
230,ROT,Refugee Olympic Team,,2016,2021

<div style="background-color:#FCB030;padding:0px; color:white;">
    <h3 style="padding-left: 40px;">Créer une itération pour récupérer tout les pays</h3>
</div>

**DEFINITION :**
- **Itération :** Processus consistant à répéter une suite d'instructions, que ce soit par l'utilisation d'une fonction récursive ou d'une boucle.

- **Boucle infinie :** Une boucle dont la condition de terminaison n'est jamais remplie, ce qui la fait s'exécuter indéfiniment.

In [11]:
#le i est la lettre du compteur 
i = 0

#Zip permet de chercher plusieurs listes et on doit la determiner dans le for 
for code_pays,nom_pays in zip(df_country.Code,df_country.Country):
    
    url = "http://olympanalyt.com/OlympAnalytics.php?param_pagetype=Medals&param_dbversion=&param_country="+ code_pays +"&param_games=ALL&param_sport=ALL"
    html_brut = GetHTML(url)
    if i == 0:
        i += 1 #incrementation , on ajoute 1 pour creer un dataframe 
        df_final = GetDataframe(html_brut)
    else :
        df_final = pd.concat([df_final,GetDataframe(html_brut)],ignore_index = True)

Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.
Response OK, continue.

In [12]:
df_final.describe()

,medal,country,athlete_name,games,sport,event
count,20281,20281,20281,20281,20281,20281
unique,3,155,16338,25,79,709
top,3,United States,,United States,Athletics,individual
freq,7052,2959,423,2628,3087,602

In [15]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20281 entries, 0 to 20280
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   medal         20281 non-null  object
 1   country       20281 non-null  object
 2   athlete_name  20281 non-null  object
 3   games         20281 non-null  object
 4   sport         20281 non-null  object
 5   event         20281 non-null  object
dtypes: object(6)
memory usage: 950.8+ KB

<div style="background-color:#0082C7;padding:0px; color:white;">
    <h2 style="padding-left: 40px;">CSV</h2>
</div>

In [14]:
df_final.to_csv('df_final.csv',index = False)

In [2]:
strings = "Coucou je suis Yohan"

print(strings)

Coucou je suis Yohan